server:
  port: 80

spring:
  application:
    name: cloud-consum-order80
  cloud:
    consul:
      host: 192.168.1.14
      port: 8500
      discovery:
        service-name: cloud-consum-order80
        prefer-ip-address: true
        heartbeat:
          enabled: true

        health-check-path: health